# Site settings
title: "Your Name"
name: "Your Name"
description: "Personal portfolio and academic website"
url: "https://yourusername.github.io" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/

# Collections
collections:
  publications:
    output: true
    permalink: /publication/:path/
  talks:
    output: true
    permalink: /talk/:path/
  posts:
    output: true
    permalink: /:categories/:title/
  projects:
    output: true
    permalink: /project/:path/

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Pagination
paginate: 5
paginate_path: /blog/page:num/

# Social media
twitter:
  username: yourtwitterhandle
  card: summary

# Google Analytics
google_analytics: UA-XXXXXXXX-X

# Author information
author:
  name: "Your Name"
  avatar: "bio-photo.jpg"
  bio: "Your bio here"
  location: "Your Location"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:your.email@example.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/yourusername"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/yourusername"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/yourtwitterhandle"

# Site footer
footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:your.email@example.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/yourusername"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/yourusername"

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  # _talks
  - scope:
      path: ""
      type: talks
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  # _projects
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true